name: Build documentation and pack
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.6                              # TODO: set required version of DoxyGen
          packchk-version: 1.3.98                             # TODO: set required version of PackChk
          gen-doc-script: ./doc/gen_doc.sh                    # TODO: set path to documentation generator script, leave empty or remove to skip
          check-links-script: ./doc/check_links.sh            # TODO: set path to link checker script, leave empty or remove to skip
          doc-path: ./doc/html/                               # TODO: set path to generated documentation, leave empty or remove to skip
          gen-pack-script: ./gen_pack.sh --no-preprocess      # TODO: set path to pack generator script, leave empty or remove to skip
          gen-pack-output: ./output                           # TODO: set path to folder with generated pack archive(s), leave empty or remove to skip
          gh-pages-branch: gh-pages                           # TODO: set branch name to deploy generated documentation to, set empty to skip
          gh-pages-deploy: gh-pages.yml                       # TODO: set name of deploy workflow to be triggered, set empty to skip
  