name: Sanity check
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    name: Workflow action
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          working-directory: sanity-check
          doxygen-version: 1.9.6
          packchk-version: 1.4.1
          gen-doc-script: ./check-doxygen.sh
          doc-path: ./Documentation/html
          gen-pack-script: ./check-pack.sh
          gen-pack-output: ./output

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Verify artifacts
        run: |
          test -f artifacts/pack/*.pack || (echo "::error::pack artifact not found", exit 1)
          test -f artifacts/documentation/index.html || (echo "::error::documentation artifact not found", exit 1)

